### ISSUE TITLE
Are rclone_secret_key_id and rclone_secret_key needed?

### ISSUE THREAD

**Issue by jakubberezowski** [gfkse/terraform-aws-airflow-ecs#5]
Hi,
I'm wondering if the following vars are needed:
* [rclone_secret_key_id][secret_key_id]
* [rclone_secret_key][secret_key]

These are passed to [ecs_container_instances.tf][ecs_container_instances.tf]. But the file does not contain such template vars: [/templates/user_data.sh][user_data.sh] and the dags are synced by mounted volumes via efs.

The question is if those could be safely removed.

[ecs_container_instances.tf]: https://github.com/gfkse/terraform-aws-airflow-ecs/blob/master/ecs_container_instances.tf#L9-L10
[secret_key_id]: https://github.com/gfkse/terraform-aws-airflow-ecs/blob/master/variables.tf#L147-L150
[secret_key]: https://github.com/gfkse/terraform-aws-airflow-ecs/blob/master/variables.tf#L136-L139
[user_data.sh]: https://github.com/gfkse/terraform-aws-airflow-ecs/blob/master/templates/user_data.sh

**Comment by edhipat** [comment]
You are right. They are not used anymore and therefore can be removed safely.
The part in /templates/user_data.sh where rclone was used for S3 sync is also removed, so it should be safe to remove them.

**Comment by edhipat** [comment]
https://github.com/gfkse/terraform-aws-airflow-ecs/blob/master/templates/user_data.sh
